### PR TITLE
Update: Change pipeline to use ENV vars

### PR DESCRIPTION
**Pull request by adodge-bcg**
# Description

This PR includes the following proposed change(s):

- Used for refactoring of the pipeline (SPDBCSC-578)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Tested locally.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by adodge-bcg** [comment]
> should frontend-env.js file be gitignored?

It could be. It is an empty file and is just there so the import in the index doesn't throw an error

**Comment by sdevalapurkar-bcgov** [comment]
lets ignore it then 👍

**Comment by sdevalapurkar-bcgov** [comment]
This LGTM, can it be merged?

**Comment by sdevalapurkar-bcgov** [comment]
any documentation changes that need to be added to explain the env var added and stuff? if it is just pipeline using it then maybe not?

**Comment by adodge-bcg** [comment]
Should be good to merge, I can add a change to the documentation instructing to create the file to remove the console warning, but it is just an empty file and is not needed.

**Pull request merged**
